MVPDP *mkpoint(char *id, char *data, unsigned int datalen);
void printpoint(MVPDP* point);
float hamming_distance(MVPDP *pointA, MVPDP *pointB);
char *get_point_id(MVPDP *point);
unsigned int get_point_datalen(MVPDP *point);
char *get_point_data(MVPDP *point);
MVPTree *newtree(void);
void addpoint(MVPTree *tree, MVPDP *point);
void printtree(MVPTree *tree);
MVPTree *load(char *filename);
void save(char *filename, MVPTree *tree);
